version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: faerun
    ports:
    - 3306:3306
    volumes:
    - database:/var/lib/mysql
  app:
    image: faerunapp:latest
    ports:
    - 5000:5000
    depends_on:
      - db
    environment:
      MYSQL_HOST: db

volumes:
  database:
