spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/faerun
    driver-class-name: com.mysql.jdbc.Driver
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:secretpassword}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
server.error.include-stacktrace: never
